### ISSUE TITLE
including labels in the alert['object']

### ISSUE THREAD

**Issue by mina19** [reedessick/lvalertTest#1]
Hi Reed,

is it possible to include a "labels" key in the alerts that are created? I am trying to test grouper using lvalertTest but approval processor keeps crashing upon the receipt of the new lvalerts that are produced because the alert["object"] dictionary does not include the labels. 

I can work around it for now but want to make minimal changes to approval processor.

Thanks,
Mina

**Comment by reedessick** [comment]
This should be fixed by fd4e2be0e1bde85e7e9e3f60207a81823bfba7af

However, I'm a bit confused. The 'labels' field in lvalert messages for alert_type="new" announcements will (currently) *always* be an empty dictionary. It does not seem like anything useful could be extracted from this. 

Nonetheless, the [GraceDb documentation](https://gracedb.ligo.org/documentation/lvalert.html) shows that such a field is defined, and therefore FakeDb will mimic this behavior.
